name: Deploy Static Site

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v1
        with:
          path: './'  # Or '/dist' if using Tailwind
      - uses: actions/deploy-pages@v2